name:                PATProject
version:             0.1.0.0
github:              "githubuser/PATProject"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/PATProject#readme>

dependencies:
- base >= 4.7 && < 5
# TODO: use this version if template recursion is needed
#- template-haskell >= 2.22 && < 3
- template-haskell >= 2.20 && < 3
- haskell-src >= 1.0 && < 2
- haskell-src-exts >= 1.23 && < 2
- mtl >= 2.3 && < 3
- containers >= 0.6 && < 1
- composition-extra >= 2.1 && < 3
- lens >= 5.2 && < 6
- relude >= 1.2 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  PATProject-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PATProject

# TODO: separate BTA (maybe both TH and normal), specializer, and runner in separate executables

tests:
  PATProject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PATProject
